app:
  name: 'WhatEatToday'
  version: '0.0.1'
  author: 'komse'
  backend-port: '3000'
  frontend-port: '5173'

database:
  dsn: 'root:123456@tcp(127.0.0.1:3306)/whateattoday?charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 11
  max-open-conns: 114
